# Reflect

Our purpose today is to notice – what works, what doesn’t work? We’ll think about your workflows and how you collaborate.

## What are things you know about yourself and how you work? 
::: {.callout-note appearance="minimal" icon="false"}
<!---p.1--->
*What are the conditions when you do your best work? This could be things like I write best in the mornings, I am comfortable speaking up in new spaces.*

-   I **do** write (and generally work) best in the mornings.
-   I work best in 90 min - to - 2 hour blocks.
-   I need both pen and paper and an electronic document for notes.
-   I don't work well when there is distracting noise, but headphones and ambient music help a lot.
-   I need things to be organized. If they're not, it's probably the first thing I do in order to orient myself and focus.
-   I come up with good ideas when I'm away from my desk (one of the reasons I try to always have pen and paper on me).
-   I  need detailed and organized to-do lists.
-   I'm an introvert, so I think through problems better than I talk through them.
-   I don't like to have to try to hold a lot in my head at once, so that I can focus on generating ideas instead of remembering things (hence always writing everything down).
-   My flow state is usually intense and fast-paced. (I should probably slow down sometimes to pause and think strategy.)
-   I do best with clear direction / end goals.


 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::


## What software and kinds of files do you work with, and for what purposes?  

::: {.callout-note appearance="minimal" icon="false"}

<!---p.2--->

*Think across your different workflows. Where do you do your writing? How do you manage citations or versions? How do software and files connect together? If you analyze data or images, what do you use?*

-   Writing: Word
-   Citations: Zotero
-   Software: R/RStudio, sometimes Python, State, and ArcGIS
-   Version Control: Git and GitHub
  

 

  

 

 

 
 

 

  

  

 

  

  

 
:::


## How do you track tasks for your workflow? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.4--->

*You can do this think of a specific project or piece of your workflow, or multiple projects. What does an example day or week look like? Do you write notes to yourself or document your process? Do you use sticky notes, apps, a document, a calendar? How do you find things weekly or come back to something after a month, a year?*

-   I have project-specific note documents, which I treat like journals/diaries, scratch workspace, and meeting notes. I usually start work with a to-do list and thinking about flow/dependences (the orer in which I need to do things), if not revisiting and reiterating high-level strategy to reorient myself.
-   These note documents, or journals, can run into hundreds of pages. I se them to refer back to previous notes, decisions, activities, etc.
-   I rely heavily on my work calendar, as well as my personal calendar.

 

  

 

 

  

  

 

  

  

 


:::

## How do you collaborate with colleagues? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.4--->

*Who is included in your workflow? How do you share files and communicate? If you think "I work alone", consider who you talk to, how do you give and receive feedback?*

-   Communication and file-sharing take place across multiple platforms: 
  -   Email
  -   MS Teams
  -   OneDrive / Sharepoint
  -   Google Drive
  -   Organizational on-site network
  -   Github
  

 

 

 
 

 

  

  

 

  

  

 


:::

## What feels good about your workflow? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.5--->

*There are good things about your workflow. What feels good to you?*

-   My detailed project journals. I feel like nothing is ever truly lost, even if sometimes it takes me a while to find it.
-   Using VC gives me confidence to make and save code changes, even if I've rarely (if ever) leveraged it to recover old versions.
-   I'm very organized, and this contributes well to overall project management in collaborative work.
-   My intense flow focus sessions (usually in the morning) are very productive. 
  

 

  
 
 
 
  

 

  

  

 

 

 
 

 

  

  

 

  

  

 

:::

## What feels clunky about your workflow? 

::: {.callout-note appearance="minimal" icon="false"}


<!---p.5--->

*Are there places you suspect take longer than they should or could improve in other ways? Are there things you find yourself repeating a lot (copy-pasting, clicking?)*

-   Collaborative issue tracking: group notes and communication about data or methodological issues often only live in emails, Teams chats, or my personal journal. Finding them is hard, finding them quickly is harder. Especially challenging when we've made methodological choices in these fragmented correspondences.
-   I rush, and end up working inefficiently because if I had paused, I'd have realized, for example, that I'd alread solved th eissue elsewhere, or that it doesn't need solving at all.
-   Lack of clear scheduling deadlines. Sticking to my own.
  

 

  

 

 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What is top-of-mind for you?

::: {.callout-note appearance="minimal" icon="false"}

<!---p.6--->

*What might be a focus for the next few weeks?*

-   This collaborative issue tracking challenge.
-   Pausing more.
-   Finding time and space/energy to write.
-   Knowing when to write (in the course of a project or task).

 

  

 

  

  

 

  

  

 

  

 


:::
