# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*

I enjoy and get a lot out of knowledge sharing, seeing how other people do things.
I enjoy showing how I do things, too. Teaching.
 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## Where within your workflow seems like a good place to start iterating?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*

Collaborative methods. I have makeshift individual workflows, and am starting to work on projects with collaborative VC, etc. methods, and I want to further develope those, skillshare, and further advance/improve methods.

 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## Think of a good workflow you’ve seen. What felt good about it? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*

E4ST. Ethan and Sally developed an ecosystem and managed to convert the PI to, that is functional and robust and enhances both collaboration and reproducibility.
Regular (weekly or biweekly) meetings. Make sure check-ins take place, even if they end early.

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What have you seen or heard about that has you curious? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

Github issues.
Pull requests.
Actually leveraging VC to: acecss old versions, track and document IMPORTANT METHODOLOGICAL CHANGES.
Co-working meetings, maybe?

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What are some of your values?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*

- Making learning new things fun
- Making people feel included, and free to ask questions.
- Anti-gate-keeping ("gate-opening"?)
- Purpose
- Learning/teaching new skills that ultimately make people's jobs easier and make more time for the fun/important/interesting stuff.
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

::: {.callout-caution appearance="minimal" icon="false"}


<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*

- I try to be early and prepared for meetings.
- Consider and create time/space for the introverts.
- Follow-through
- Asking for help, honesty, creating safe space for others to ask for help.
- Adaptive management
- Listening

 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What would it look like to connect your values more with your workflow?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

Implementing collaborative tools, but in a way that does not make people feel overwhelemed, but, instead, empowered.
[Fear: I feel like I need to become an expert first in order to effectively chamption, implement, and teach new methods.]
* Suggested solution: Could find just ONE like-minded person on a team to work with to try new things!

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
